### ISSUE TITLE
ubuntu 16.04  cat in.json | jsoncsv | mkexcel > out.csv ERROR

### ISSUE THREAD

**Issue by yusmile0618** [alingse/jsoncsv#19]
ubuntu 16.04  
cat in.json | jsoncsv | mkexcel > out.csv 

ERROR

Traceback (most recent call last):
  File "/usr/local/bin/jsoncsv", line 9, in <module>
    load_entry_point('jsoncsv==2.0.8', 'console_scripts', 'jsoncsv')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/jsoncsv/main.py", line 50, in jsoncsv
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 3 (char 2)

THANKS

**Comment by alingse** [comment]
不知道是不是和这个 issue 一样的 https://github.com/alingse/jsoncsv/issues/9

这边需要 1行一行的json 数据，如果是美化的可能需要处理一下。
