### ISSUE TITLE
Python下使用的问题

### ISSUE THREAD

**Issue by xixi23** [alingse/jsoncsv#27]
编程新人。python3(spider)+windows下使用，最后一行错误SyntaxError: invalid syntax 

code如下：
import os
import sys
import json
import jsoncsv

file_dir = '../data/raw/103_course_content/02_course_bought_together/9287.json'
    
cat 9287.json |jsoncsv |mkexcel > output.csv

**Comment by alingse** [comment]
这个是命令行工具，你应该在 cmd 中打开，但是我不清楚 Windows 是否支持管道，可以一步一步来

**Comment by alingse** [comment]
jsoncsv fileA.json fileB.json

mkexcel fileB.json fileB.csv

**Comment by xixi23** [comment]
谢谢！那如果想要批量转换csv也可以实现吗？

**Comment by xixi23** [comment]
我是在mac上安装了parallel来运行windows10
jsoncsv fileA.json fileB.json运行成功，
但是mkexcel fileB.json fileB.csv 出现以下问题：
Traceback (most recent call last):
  File "c:\...\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\...\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\...\Anaconda3\Scripts\mkexcel.exe\__main__.py", line 9, in <module>
  File "c:\...\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\...\anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\...\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\...\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\...\anaconda3\lib\site-packages\jsoncsv\main.py", line 97, in mkexcel
    dumpexcel(input, output, type_, read_row=row, sort_type=sort_)
  File "c:\...\anaconda3\lib\site-packages\jsoncsv\dumptool.py", line 172, in dumpexcel
    dump.dump()
  File "c:\...\anaconda3\lib\site-packages\jsoncsv\dumptool.py", line 41, in dump
    self.dump_file()
  File "c:\...\anaconda3\lib\site-packages\jsoncsv\dumptool.py", line 89, in dump_file
    self.write_headers()
  File "c:\...\anaconda3\lib\site-packages\jsoncsv\dumptool.py", line 109, in write_headers
    self.fout.write(header)
TypeError: a bytes-like object is required, not 'str'

**Comment by alingse** [comment]
@xixi23 哪个版本？我尝试下，可能又是 python3 的 bytes /str 的问题

**Comment by duramen** [comment]
windows   python3版本，执行jsoncsv命令，经常出现unicodeEncodeError问题：
![image](https://user-images.githubusercontent.com/10753707/65760356-713d0080-e14f-11e9-8b8b-9ecd4034b2f6.png)

**Comment by alingse** [comment]
@duramen  可能是编码问题。我想想怎么做。 windows 用的是 gbk 估计不支持 utf8 ？
你的原始文件可以传一点上来么。或者贴一些命令。

**Comment by duramen** [comment]
> @duramen 可能是编码问题。我想想怎么做。 windows 用的是 gbk 估计不支持 utf8 ？
> 你的原始文件可以传一点上来么。或者贴一些命令。

数据样例
{"name": "\u4efb\u94c1\u2e95"}
{"name": "\u95eb\u5e05"}

**Comment by alingse** [comment]
我重新开一个了 @duramen  只能有空再看了。

**Comment by alingse** [comment]
@xixi23 @duramen 
可以试下最新版看下，应该是ok 了。
实在不行可以在 Git Bash 里面执行。
