### ISSUE TITLE
Getting exception when running Json to CSV tool

### ISSUE THREAD

**Issue by guru22udupi** [alingse/jsoncsv#42]
Am using centOS 7 and using python 2.7. Am getting following exception when try to convert json to CSV

[root@SIQ4L_6709 jsoncsv-2.2.4]# cat exportAttributes_matter.json | jsoncsv | mkexcel > output.csv
Traceback (most recent call last):
  File "/usr/bin/jsoncsv", line 9, in <module>
    load_entry_point('jsoncsv==2.2.4', 'console_scripts', 'jsoncsv')()
  File "/usr/lib/python2.7/site-packages/click-7.1.1-py2.7.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-7.1.1-py2.7.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-7.1.1-py2.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-7.1.1-py2.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/jsoncsv/main.py", line 60, in jsoncsv
  File "build/bdist.linux-x86_64/egg/jsoncsv/jsontool.py", line 160, in convert_json
  File "build/bdist.linux-x86_64/egg/jsoncsv/jsontool.py", line 145, in gen_objs
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 1 column 2 (char 1)

**Comment by alingse** [comment]
`jsoncsv` only accept a json file that each line is a json string.

if your `exportAttributes_matter.json` is  beautiful print json like:
```
{
  "a": 1,
 "b": 2,
}
{
  "a": 2,
 "b": 4,
}
```
jsoncsv read each line and try loads it will fail.

you can try `cat exportAttributes_matter.json | jq -r '' |jsoncsv|mkexcel > output.csv`

jq is command line json text processor the option `jq -r ''` will transform your exportAttributes_matter.json more compact.

```
{"a":1, "b":2}
{"a":2, "b":4}
```
and the jsoncsv && mkexcel will output
```
a,b
1,2
2,4
```
your can try again.

Oh god. forgive for my poor English.  I hope you can understand what I mean.

**Comment by guru22udupi** [comment]
Thanks very much for the timely help. With json format as
{"a":1, "b":2}
{"a":2, "b":4}

Resolved this issue

**Comment by alingse** [comment]
@guru22udupi ok I will close this issue.
